### ISSUE TITLE
How do I add image to pdf using itext7 in unity c#?

### ISSUE THREAD

**Issue by Divyanshu-del** [thombrink/itext7.pdfimage#7]
I am trying to **add an image** to my **pdf document using itext7** but I am getting **DirectoryNotFoundException**. I was using itextsharp which worked but the same is not the case with itext7, some similar questions from StackOverflow showed me how it's done but it doesn't read the file which is in the **Assets Folder**. Here is my code:

 ` var exportFolder = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
    var exportFile = System.IO.Path.Combine(exportFolder, "myfile.pdf");`

    //Create Writer
    var writer = new PdfWriter(exportFile);

    //Create Pdf Document Object
    var pdf = new PdfDocument(writer);

    //Create A Document
    Document document = new Document(pdf, PageSize.A4);

    //Add Cover Page 1

    ImageData imagedata = ImageDataFactory.Create("Ganesh.jpg");
    iText.Layout.Element.Image coverImage = new iText.Layout.Element.Image(imagedata);

    document.Add(coverImage);

    document.Add(new iText.Layout.Element.AreaBreak());
    document.Close();`

This is the error I get after running the function through button click event:
`DirectoryNotFoundException: Could not find a part of the path "C:\Users\Public\Documents\LO%20SHU%20GRID%20Windows\Ganesh.jpg".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <7ba07f088431485bb722f3b3373e87ee>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) (at <7ba07f088431485bb722f3b3373e87ee>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) (at <7ba07f088431485bb722f3b3373e87ee>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
iText.IO.Util.UrlUtil.OpenStream (System.Uri url) (at <57da1b8d8a184e278c732544ebe6412a>:0)
iText.IO.Image.ImageDataFactory.ReadImageType (System.Uri source) (at <57da1b8d8a184e278c732544ebe6412a>:0)
Rethrow as IOException: io.exception
iText.IO.Image.ImageDataFactory.ReadImageType (System.Uri source) (at <57da1b8d8a184e278c732544ebe6412a>:0)
iText.IO.Image.ImageDataFactory.CreateImageInstance (System.Uri source, System.Boolean recoverImage) (at <57da1b8d8a184e278c732544ebe6412a>:0)
iText.IO.Image.ImageDataFactory.Create (System.Uri url, System.Boolean recoverImage) (at <57da1b8d8a184e278c732544ebe6412a>:0)
iText.IO.Image.ImageDataFactory.Create (System.String filename, System.Boolean recoverImage) (at <57da1b8d8a184e278c732544ebe6412a>:0)
iText.IO.Image.ImageDataFactory.Create (System.String filename) (at <57da1b8d8a184e278c732544ebe6412a>:0)
Panel.EnglishPdf () (at Assets/Scripts/Panel.cs:5755)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:66)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)`
I would be very grateful if any kind soul would help me fix this error.

**Comment by Jawvig** [comment]
I think you've got the wrong repo. This is for a library built on top of iText7 for the purpose of generating images of the rendered PDF. I think you should be directing this to StackOverflow or https://itextpdf.com/en/support

**Comment by Jawvig** [comment]
Having said that, it looks like it's not looking for the JPG file in the "Assets" directory, wherever that is. Try and specify a full path to the JPG and see if that works. Alternatively you could read the file into byte array by using standard .NET classes and pass that byte array to `ImageDataFactory.Create`.

**Comment by Divyanshu-del** [comment]
> Having said that, it looks like it's not looking for the JPG file in the "Assets" directory, wherever that is. Try and specify a full path to the JPG and see if that works. Alternatively you could read the file into byte array by using standard .NET classes and pass that byte array to `ImageDataFactory.Create`.

Thanks man.. it wasn't your area still you gave me a hint. I'll do it.

**Comment by Divyanshu-del** [comment]
Converting image to byte array fixed it... Thanks a lot man.
